### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by clekstro** [mbj/vanguard#5]
As there's not a gem available from rubygems yet, what is the best option to install?  Adding to the Gemfile and pointing at this repo doesn't seem to work:

1.9.3-p429 :001 > require 'vanguard'
LoadError: cannot load such file -- vanguard

**Comment by mbj** [comment]
@clekstro `bundle exec irb` solves the problem?

**Comment by clekstro** [comment]
Thanks!
