### ISSUE TITLE
Validation messages

### ISSUE THREAD

**Issue by lukelex** [mbj/vanguard#7]
Is there any plans to add user readable messages for Violations?

**Comment by mbj** [comment]
@lukelex Plans: Lots ;)

Time to add them soon: Zero.

I'll happily accept contributions.

IMHO Validation messages should be implemented via a decorator.

``` ruby
validator = your_validator.run(resource)
unless validator.success?
  render_your_view_with(CoolLanguageSpecificMessageDecorator.new(validator))
end
```

**Comment by dkubb** [comment]
@mbj so the idea with this is that the validator will be objects you can introspect to find out the state of the validation, and a decorator should provide the translation of the messages into other languages and/or user defined messages?

**Comment by mbj** [comment]
@dkubb Yes. But vanguards internals are not very well thought. I think an evaluation tree such as ducktrap result objects would be the perfect approach. I expect vanguard to be a ducktrap frontend once released.
